version: 2.1
jobs:
  build:
    docker:
        - image: circleci/python:3.9
    steps:
        - checkout
        - run: ls -a
        - run: |
            echo "Hello World"
            python3 --version
        - run: |
            pip install pytest
            pytest tests/

