version: 2.1
jobs:
    test-python39:
        docker:
            - image: circleci/python:3.9
        steps:
            - checkout
            - run: ls -a
            - run: |
                echo "Hello World"
                python3 --version
            - run: |
                pip install pytest
                pytest -v tests/

    test-python38:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: ls -a
            - run: |
                echo "Hello World"
                python3 --version
            - run: |
                pip install pytest
                pytest -v tests/

    test-python37:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: ls -a
            - run: |
                echo "Hello World"
                python3 --version
            - run: |
                pip install pytest
                pytest -v tests/



workflows:
    version: 2
    python-tests:
        jobs:
            - test-python39
            - test-python38
    old-python-tests:
        jobs:
            - test-python37
